---
title: "Qualitative data analysis"
format: pdf
---

```{r}
#| message: false
library(tidyverse)
library(here)
```

## Data context themes
### Data wrangling lecture A

Read in data
```{r}
author_b_reviews_og <- read_csv(
  here(
    "data", 
    "02-independent-reviews",
    "hw-context-reasons-themes-author_b-lec-a.csv"
  ),
  show_col_types = FALSE
) 

author_b_reviews <- author_b_reviews_og|> 
  select(-contains("reason")) |> 
  select(-contains("notes")) |> 
  rename(ds_context1_theme_author_b = ds_context1_theme) |> 
  rename(ds_context2_theme_author_b = ds_context2_theme) |> 
  rename(ds_context3_theme_author_b = ds_context3_theme) |> 
  rename(nonspecific_theme_author_b = nonspecific_theme)
  

author_a_reviews_og <- read_csv(
  here(
    "data", 
    "02-independent-reviews", 
    "hw-context-reasons-themes-author_a.csv"
  ),
  show_col_types = FALSE
) 

author_a_reviews <- author_a_reviews_og|> 
  select(-contains("reason")) |> 
  select(-contains("notes")) |> 
  rename(ds_context1_theme_author_a = ds_context1_theme) |> 
  rename(ds_context2_theme_author_a = ds_context2_theme) |> 
  rename(ds_context3_theme_author_a = ds_context3_theme) |> 
  rename(nonspecific_theme_author_a = nonspecific_theme)
```

Merge certain columns into one data frame
```{r}
lec_a_reviews <- author_b_reviews |> 
  full_join(author_a_reviews) |> 
  arrange(assignment_id) |>
  mutate(ds_context1_theme_resolved = case_when(
    ds_context1_theme_author_a == ds_context1_theme_author_b ~ ds_context1_theme_author_a,
    TRUE ~ NA
  )) |> 
  mutate(ds_context2_theme_resolved = case_when(
    ds_context2_theme_author_a == ds_context2_theme_author_b ~ ds_context2_theme_author_a,
    TRUE ~ NA
  )) |>
  mutate(ds_context3_theme_resolved = case_when(
    ds_context3_theme_author_a == ds_context3_theme_author_b ~ ds_context3_theme_author_a,
    TRUE ~ NA
  )) |>
  mutate(nonspecific_theme_resolved = case_when(
    nonspecific_theme_author_a == nonspecific_theme_author_b ~ nonspecific_theme_author_a,
    nonspecific_theme_author_a == "no info" & is.na(nonspecific_theme_author_b) ~ "no info",
    TRUE ~ NA
  )) |>
  filter(section == "A") |> 
  select( 
    "assignment_id",
    "random_id",
    "hw",
    "section",
    "choice",
    "context",
    "context_q1_response",
    "context_q2_response",
    "context_q3_response",
    "ds_context1_theme_author_a",
    "ds_context1_theme_author_b",
    "ds_context1_theme_resolved",
    "ds_context2_theme_author_a",
    "ds_context2_theme_author_b",
    "ds_context2_theme_resolved",
    "ds_context3_theme_author_a",
    "ds_context3_theme_author_b",
    "ds_context3_theme_resolved",
    "nonspecific_theme_author_a",
    "nonspecific_theme_author_b",
    "nonspecific_theme_resolved"
  )

write_csv(lec_a_reviews, here("data", "03-cleaned-data", "combined-reviews-lec-a.csv"))
```

### Data wrangling lecture B

Read in data
```{r}
author_b_reviews_og <- read_csv(
  here(
    "data", 
    "02-independent-reviews", 
    "hw-context-reasons-themes-author_b-lec-b.csv"
  ),
  show_col_types = FALSE
) 

author_b_reviews <- author_b_reviews_og|> 
  select(-contains("reason")) |> 
  select(-contains("notes")) |> 
  rename(ds_context1_theme_author_b = ds_context1_theme) |> 
  rename(ds_context2_theme_author_b = ds_context2_theme) |> 
  rename(ds_context3_theme_author_b = ds_context3_theme) |> 
  rename(nonspecific_theme_author_b = nonspecific_theme)
  

author_a_reviews_og <- read_csv(
  here(
    "data", 
    "02-independent-reviews",
    "hw-context-reasons-themes-author_a.csv"
  ),
  show_col_types = FALSE
) 

author_a_reviews <- author_a_reviews_og|> 
  select(-contains("reason")) |> 
  select(-contains("notes")) |> 
  rename(ds_context1_theme_author_a = ds_context1_theme) |> 
  rename(ds_context2_theme_author_a = ds_context2_theme) |> 
  rename(ds_context3_theme_author_a = ds_context3_theme) |> 
  rename(nonspecific_theme_author_a = nonspecific_theme)
```

Merge certain columns into one data frame
```{r}
lec_b_reviews <- author_b_reviews |> 
  full_join(author_a_reviews) |> 
  arrange(assignment_id) |>
  mutate(ds_context1_theme_resolved = case_when(
    ds_context1_theme_author_a == ds_context1_theme_author_b ~ ds_context1_theme_author_a,
    TRUE ~ NA
  )) |> 
  mutate(ds_context2_theme_resolved = case_when(
    ds_context2_theme_author_a == ds_context2_theme_author_b ~ ds_context2_theme_author_a,
    TRUE ~ NA
  )) |>
  mutate(ds_context3_theme_resolved = case_when(
    ds_context3_theme_author_a == ds_context3_theme_author_b ~ ds_context3_theme_author_a,
    TRUE ~ NA
  )) |>
  mutate(nonspecific_theme_resolved = case_when(
    nonspecific_theme_author_a == nonspecific_theme_author_b ~ nonspecific_theme_author_a,
    nonspecific_theme_author_a == "no info" & is.na(nonspecific_theme_author_b) ~ "no info",
    TRUE ~ NA
  )) |>
  filter(section == "B") |> 
  select( 
    "assignment_id",
    "random_id",
    "hw",
    "section",
    "choice",
    "context",
    "context_q1_response",
    "context_q2_response",
    "context_q3_response",
    "ds_context1_theme_author_a",
    "ds_context1_theme_author_b",
    "ds_context1_theme_resolved",
    "ds_context2_theme_author_a",
    "ds_context2_theme_author_b",
    "ds_context2_theme_resolved",
    "ds_context3_theme_author_a",
    "ds_context3_theme_author_b",
    "ds_context3_theme_resolved",
    "nonspecific_theme_author_a",
    "nonspecific_theme_author_b",
    "nonspecific_theme_resolved"
  ) |> 
  arrange(hw, context, random_id)

write_csv(lec_b_reviews, here("data", "03-cleaned-data", "combined-reviews-lec-b.csv"))
```
## Choice themes 

### Lecture A

```{r}
choice_reviews_author_a_og <- read_csv(
  here("data", "02-independent-reviews", "survey-choice-themes-author_a.csv"),
  show_col_types = FALSE
)

choice_reviews_author_b_og <- read_csv(
  here("data", "02-independent-reviews", "survey-choice-themes-author_b.csv"),
  show_col_types = FALSE
)

choice_reviews_author_b <- choice_reviews_author_b_og |> 
  select(-contains("reason")) |>
  select(-contains("nonspecific")) |> 
  rename(negative_theme_author_b = negative_theme) |> 
  rename(impartial_theme_author_b = impartial_theme) |> 
  rename(positive_theme_author_b = positive_theme)

choice_reviews_author_a <- choice_reviews_author_a_og |> 
  select(-contains("reason")) |>
  select(-contains("nonspecific")) |> 
  rename(negative_theme_author_a = negative_theme) |> 
  rename(impartial_theme_author_a = impartial_theme) |> 
  rename(positive_theme_author_a = positive_theme)
```

```{r}
choice_reviews_lec_a <- choice_reviews_author_b |> 
  full_join(choice_reviews_author_a) |> 
  arrange(random_id) |>
  mutate(negative_theme_resolved = case_when(
    negative_theme_author_a == negative_theme_author_b ~ negative_theme_author_a,
    TRUE ~ NA
  )) |> 
  mutate(impartial_theme_resolved = case_when(
    impartial_theme_author_a == impartial_theme_author_b ~ impartial_theme_author_a,
    TRUE ~ NA
  )) |>
  mutate(positive_theme_resolved = case_when(
    positive_theme_author_a == positive_theme_author_b ~ positive_theme_author_a,
    TRUE ~ NA
  )) |>
  filter(section == "A") |> 
  select( 
    "random_id",
    "section",
    "student_response",
    "negative_theme_author_a",
    "negative_theme_author_b",
    "negative_theme_resolved",
    "impartial_theme_author_a",
    "impartial_theme_author_b",
    "impartial_theme_resolved",
    "positive_theme_author_a",
    "positive_theme_author_b",
    "positive_theme_resolved"
  )

write_csv(choice_reviews_lec_a, here("data", "03-joint-reviews", "combined-choice-reviews-lec-a.csv"))
```



### Lecture B

```{r}
choice_reviews_author_a_og <- read_csv(
  here("data", "02-independent-reviews", "survey-choice-themes-author_a.csv"),
  show_col_types = FALSE
)

choice_reviews_author_b_og <- read_csv(
  here("data", "02-independent-reviews", "survey-choice-themes-author_b.csv"),
  show_col_types = FALSE
)

choice_reviews_author_b <- choice_reviews_author_b_og |> 
  select(-contains("reason")) |>
  select(-contains("nonspecific")) |> 
  rename(negative_theme_author_b = negative_theme) |> 
  rename(impartial_theme_author_b = impartial_theme) |> 
  rename(positive_theme_author_b = positive_theme)

choice_reviews_author_a <- choice_reviews_author_a_og |> 
  select(-contains("reason")) |>
  select(-contains("nonspecific")) |> 
  rename(negative_theme_author_a = negative_theme) |> 
  rename(impartial_theme_author_a = impartial_theme) |> 
  rename(positive_theme_author_a = positive_theme)
```

```{r}
choice_reviews_lec_b <- choice_reviews_author_b |> 
  full_join(choice_reviews_author_a) |> 
  arrange(random_id) |>
  mutate(negative_theme_resolved = case_when(
    negative_theme_author_a == negative_theme_author_b ~ negative_theme_author_a,
    TRUE ~ NA
  )) |> 
  mutate(impartial_theme_resolved = case_when(
    impartial_theme_author_a == impartial_theme_author_b ~ impartial_theme_author_a,
    TRUE ~ NA
  )) |>
  mutate(positive_theme_resolved = case_when(
    positive_theme_author_a == positive_theme_author_b ~ positive_theme_author_a,
    TRUE ~ NA
  )) |>
  filter(section == "B") |> 
  select( 
    "random_id",
    "section",
    "student_response",
    "negative_theme_author_a",
    "negative_theme_author_b",
    "negative_theme_resolved",
    "impartial_theme_author_a",
    "impartial_theme_author_b",
    "impartial_theme_resolved",
    "positive_theme_author_a",
    "positive_theme_author_b",
    "positive_theme_resolved"
  )

write_csv(choice_reviews_lec_b, here("data", "03-joint-reviews", "combined-choice-reviews-lec-b.csv"))
```

